spring:
  application:
    name: hello-sys
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12300/eureka/
  instance:
    prefer-ip-address: true
    
server:
  port: 12301    
env: 
  dev    
